module.exports = {
    data: {
        name: 'minecraftidea',
        description: 'Start a Minecraft idea',
    },
    async execute(interaction, client) {
        await interaction.deferReply();
        const task = [
            "Build a massive #build# made of #block#",
            "Find a #struc# and make it your home",
            "Find a way to farm #material#",
            "Kill some #mob#s",
            "Get a friend and build a #build#",
            "Destroy a #struc#",
            "Build a home for a #mob#",
            "Make a #build# out of #block#",
            "Fill a double chest with #material#",
            "Create a #build# using #block# and #block#",
            "Explore a #struc# and gather its loot",
            "Build a massive upscaled #block#",
            "Defend a village from #mob#s",
            "Build a #build# around a #struc#",
            "Make a farm for #mob#s",
            "Find a #struc# and collect all the #material# inside",
            "Design a #build# using #block#, #block#, and #block#",
            "Create a hidden room in your #build#",
            "Search for a #struc# and make it a base",
            "Turn a #struc# into a defensive fortress",
            "Build a #build# that contains a #mob# enclosure",
            "Gather #material# from a #struc#",
            "Construct a #build# with #block# and #block# accents",
            "Set up a #mob# farm in a #struc#",
            "Create a series of #build#s connected by #block# pathways",
            "Rebuild a #struc# from the materials you collect",
            "Construct a #block# wall around a #struc#",
            "Find and repair a #struc#",
            "Create a complex #build# from #block# and #block#",
            "Transform a #struc# into a functional base",
            "Build a #build# that includes a #mob# spawner",
            "Make a #build# featuring #block# and #block#",
            "Clear out a #struc# and repurpose its resources",
            "Build a #build# with an #mob# habitat",
            "Find a rare #struc# and document it",
            "Construct a #build# in the shape of a #block#",
            "Make an elaborate #build# with #block# and #block# designs",
            "Establish a #mob# shelter within a #struc#",
            "Explore different #struc#s and map their locations",
            "Construct a detailed #build# using #block#",
            "Make a #build# that houses a #mob# collection",
            "Turn a #struc# into a resource gathering point",
            "Craft a #block# using resources found in a #struc#",
            "Design a large #build# with #block# decorations",
            "Transform an old #struc# into a new #build#",
            "Build a functional #build# using #block# as the primary material",
            "Set up a #mob# farm within a #struc# and gather resources",
            "Create a #build# with intricate #block# patterns",
            "Find and renovate a #struc# into a livable space",
            "Construct a #build# featuring a #mob# arena",
            "Gather resources from a #struc# and use them to build a #build#",
            "Build a detailed #build# using #block# and #block# features",
            "Find a #struc# and create a #build# that connects to it",
            "Create a large #build# with different #block# types",
            "Explore and document all #struc#s in your world",
            "Construct a #build# with functional #block# elements",
            "Design a themed #build# using #block# and #block#",
            "Find and decorate a #struc# with #block#",
            "Build a fortress around a #struc# using #block#",
            "Create a #build# with multiple #mob# habitats",
            "Turn a #struc# into an elaborate #build#",
            "Construct a #build# with #block# as the foundation and #block# as decoration"
        ];

        const material = [
            "diamond",
            "iron",
            "gold",
            "emerald",
            "redstone",
            "lapis",
            "netherite",
            "glowstone",
            "quartz",
            "obsidian",
            "string",
            "bone",
            "nether brick",
            "coal",
            "copper",
            "amethyst",
            "tnt",
            "sand",
            "gravel",
            "clay",
            "wool",
            "leather",
            "wood",
            "planks",
            "bricks",
            "stone",
            "cobblestone",
            "andesite",
            "diorite",
            "granite",
            "slime",
            "snow",
            "ice",
            "glass",
            "sandstone",
            "red sandstone",
            "wheat",
            "beetroot",
            "carrot",
            "potato",
            "melon",
            "pumpkin",
            "cactus",
            "vines",
            "lily pad",
            "sapling",
            "bone meal",
            "dye",
            "banner",
            "glazed terracotta",
            "concrete",
            "terracotta",
            "brewing stand",
            "cauldron",
            "crafting table",
            "furnace",
            "anvil",
            "smithing table",
            "grindstone",
            "blast furnace",
            "stonecutter",
            "loom",
            "composter",
            "note block",
            "jukebox",
            "bed",
            "chest",
            "trapped chest",
            "shulker box",
            "ender chest",
            "hoppers",
            "dispensers",
            "pistons",
            "sticky piston",
            "observer",
            "redstone torch",
            "lever",
            "pressure plate",
            "button",
            "tripwire hook",
            "daylight sensor",
            "trapdoor",
            "iron door",
            "wooden door",
            "sign",
            "ladder",
            "fence",
            "gate",
            "stairs",
            "slabs",
            "wall",
            "bedrock",
            "nether quartz ore",
            "lapis lazuli ore",
            "gold ore",
            "iron ore",
            "diamond ore",
            "emerald ore",
            "coal ore",
            "copper ore",
            "deepslate",
            "calcite",
            "tuff",
            "dripstone",
            "spore blossom",
            "azalea",
            "flower pot",
            "bamboo",
            "scaffolding",
            "sweet berries",
            "honeycomb",
            "honey bottle",
            "beehive",
            "beeswax",
            "candles",
            "glow berries",
            "fishing rod",
            "bow",
            "arrow",
            "crossbow",
            "trident",
            "shield",
            "map",
            "compass",
            "clock",
            "spyglass",
            "tropical fish",
            "cod",
            "salmon",
            "pufferfish",
            "squid",
            "dolphin",
            "panda",
            "fox",
            "wolf",
            "cat",
            "horse",
            "llama",
            "parrot",
            "bat",
            "ocelot",
            "villager",
            "iron golem",
            "snow golem",
            "enderman",
            "creeper",
            "zombie",
            "skeleton",
            "spider",
            "witch",
            "slime",
            "magma cube",
            "ghast",
            "blaze",
            "silverfish",
            "endermite",
            "guardian",
            "elder guardian",
            "shulker",
            "witherskeleton",
            "wither",
            "dragon egg",
            "ender dragon",
            "beacon",
            "experience bottle",
            "name tag",
            "enchanted book",
            "totem of undying",
            "emerald block",
            "diamond block",
            "gold block",
            "iron block",
            "lapis block",
            "redstone block",
            "netherite ingot",
            "netherite block",
            "copper block",
            "amethyst block",
            "wool block",
            "netherite scrap",
            "ancient debris"
        ];
        const block = [
            "stone",
            "granite",
            "diorite",
            "andesite",
            "cobblestone",
            "bedrock",
            "sand",
            "red sandstone",
            "grass block",
            "dirt",
            "coarse dirt",
            "podzol",
            "crimson nylium",
            "warped nylium",
            "bamboo",
            "soul sand",
            "soul soil",
            "sandstone",
            "red sandstone",
            "gravel",
            "clay",
            "bricks",
            "mossy cobblestone",
            "obsidian",
            "diamond ore",
            "iron ore",
            "coal ore",
            "gold ore",
            "emerald ore",
            "lapis lazuli ore",
            "redstone ore",
            "nether quartz ore",
            "copper ore",
            "deepslate",
            "deepslate diamond ore",
            "deepslate iron ore",
            "deepslate coal ore",
            "deepslate gold ore",
            "deepslate emerald ore",
            "deepslate lapis lazuli ore",
            "deepslate redstone ore",
            "deepslate copper ore",
            "tuff",
            "calcite",
            "dripstone block",
            "pointed dripstone",
            "amethyst block",
            "budding amethyst",
            "ender chest",
            "chest",
            "trapped chest",
            "shulker box",
            "furnace",
            "blast furnace",
            "smoker",
            "campfire",
            "composter",
            "brewing stand",
            "enchanting table",
            "anvil",
            "smithing table",
            "grindstone",
            "stonecutter",
            "loom",
            "blast furnace",
            "barrel",
            "cauldron",
            "note block",
            "jukebox",
            "daylight sensor",
            "redstone lamp",
            "piston",
            "sticky piston",
            "observer",
            "dispenser",
            "dropper",
            "hopper",
            "target",
            "sculk sensor",
            "frosted ice",
            "soul lantern",
            "soul torch",
            "beacon",
            "nether portal",
            "end portal frame",
            "bed",
            "sign",
            "wooden door",
            "iron door",
            "trapdoor",
            "ladder",
            "fence",
            "fence gate",
            "gate",
            "wall",
            "door",
            "trapdoor",
            "piston",
            "sticky piston",
            "slime block",
            "honey block",
            "hay bale",
            "cobweb",
            "web",
            "grass",
            "tall grass",
            "fern",
            "dead bush",
            "lily pad",
            "water lily",
            "flower pot",
            "cactus",
            "sugar cane",
            "kelp",
            "sea pickle",
            "coral",
            "coral fan",
            "dead coral",
            "dead coral fan",
            "seagrass",
            "sea lantern",
            "conduit",
            "beehive",
            "bees nest",
            "honey block",
            "honeycomb block",
            "bamboo",
            "scaffolding",
            "loom",
            "smithing table",
            "grindstone",
            "blast furnace",
            "smoker",
            "barrel",
            "campfire",
            "cobblestone wall",
            "mossy cobblestone wall",
            "stone brick wall",
            "mossy stone brick wall",
            "prismarine",
            "prismarine brick",
            "dark prismarine",
            "end stone",
            "end stone brick",
            "purpur block",
            "purpur pillar",
            "purpur slab",
            "purpur stairs",
            "polished andesite",
            "polished diorite",
            "polished granite",
            "smooth stone",
            "smooth sandstone",
            "smooth quartz",
            "smooth basalt",
            "basalt",
            "blackstone",
            "polished blackstone",
            "polished blackstone bricks",
            "cracked polished blackstone bricks",
            "chiseled polished blackstone",
            "cracked blackstone bricks",
            "infested stone",
            "infested cobblestone",
            "infested mossy cobblestone",
            "infested stone brick",
            "infested mossy stone brick",
            "scaffolding",
            "lantern",
            "soul lantern",
            "soul torch",
            "chain",
            "chain command block",
            "command block",
            "repeating command block",
            "conditional command block",
            "structure block",
            "structure void",
            "jigsaw",
            "light",
            "end rod",
            "lectern",
            "bell",
            "campfire",
            "soul campfire",
            "tnt",
            "redstone block",
            "netherite block",
            "gold block",
            "iron block",
            "lapis block",
            "emerald block",
            "diamond block",
            "copper block",
            "amethyst block",
            "crimson stem",
            "crimson hyphae",
            "warped stem",
            "warped hyphae",
            "crimson planks",
            "warped planks",
            "crimson slabs",
            "warped slabs",
            "crimson stairs",
            "warped stairs",
            "crimson fence",
            "warped fence",
            "crimson trapdoor",
            "warped trapdoor",
            "crimson door",
            "warped door",
            "crimson button",
            "warped button",
            "crimson pressure plate",
            "warped pressure plate",
            "crimson sign",
            "warped sign",
            "crimson door",
            "warped door"
        ];
        const build = [
            "house",
            "castle",
            "fortress",
            "tower",
            "farm",
            "village",
            "city",
            "town",
            "mine",
            "tunnel",
            "bridge",
            "road",
            "railway",
            "railway station",
            "railway tunnel",
            "railway bridge",
            "ship",
            "boat",
            "submarine",
            "airplane",
            "helicopter",
            "hot air balloon",
            "rocket",
            "space station",
            "planet",
            "moon",
            "statue",
            "monument",
            "memorial",
            "graveyard",
        ]
        const mobs = [
            "zombie",
            "skeleton",
            "creeper",
            "spider",
            "witch",
            "enderman",
            "silverfish",
            "magma cube",
            "blaze",
            "ghast",
            "slime",
            "guardian",
            "elder guardian",
            "shulker",
            "wither skeleton",
            "wither",
            "end dragon",
            "zombie piglin",
            "piglin",
            "hoglin",
            "strider",
            "ravager",
            "pillager",
            "evoker",
            "vindicator",
            "illusioner",
            "phantom",
            "drowned",
            "pufferfish",
            "tropical fish",
            "cod",
            "salmon",
            "squid",
            "dolphin",
            "panda",
            "fox",
            "wolf",
            "cat",
            "ocelot",
            "horse",
            "donkey",
            "mule",
            "llama",
            "parrot",
            "bat",
            "villager",
            "iron golem",
            "snow golem",
            "bee",
            "wither skeleton",
            "enderman",
            "shulker",
            "phantom",
            "stray",
            "husk",
            "zombified piglin",
            "strider",
            "piglin brute",
            "cave spider",
            "baby zombie",
            "baby zombie villager",
            "evoker fang",
            "vex",
            "illusioner",
            "witch",
            "wandering trader",
            "snow fox",
            "tropical fish",
            "pufferfish",
            "cod",
            "salmon",
            "glow squid",
            "axolotl",
            "goat",
            "mushroom cow",
            "spawner",
            "mushroom",
            "fish",
            "turtle",
            "stray",
            "husk",
            "drowned",
            "fish",
            "enderman",
            "panda",
            "polar bear",
            "strider",
            "piglin",
            "zombified piglin",
            "hoglin",
            "wither skeleton",
            "shulker",
            "phantom",
            "elder guardian",
            "guardian",
            "evoker",
            "vindicator",
            "pillager",
            "panda",
            "fox",
            "wolf",
            "ocelot",
            "cat",
            "horse",
            "llama",
            "parrot",
            "donkey",
            "mule",
            "trader llama",
            "wandering trader",
            "vex",
            "illager",
            "ravager",
            "jungle spider",
            "forest spider",
            "desert spider",
            "swamp spider",
            "cave spider",
            "endermite",
            "blaze",
            "magma cube",
            "phantom",
            "ghast",
            "silverfish",
            "guardian",
            "elder guardian",
            "pufferfish",
            "cod",
            "salmon",
            "tropical fish",
            "glow squid",
            "axolotl",
            "goat",
            "piglin brute",
            "strider",
            "zombified piglin",
            "hoglin",
            "enderman",
            "wither skeleton",
            "end dragon",
            "beetroot",
            "bee",
            "squid",
            "fish",
            "frog",
            "snail",
            "axolotl",
            "chicken",
            "cow",
            "sheep",
            "goat",
            "rabbit",
            "horse",
            "donkey",
            "mule",
            "llama",
            "parrot",
            "cat",
            "dog",
            "bat",
            "villager",
            "iron golem",
            "snow golem",
            "jockey",
            "wither boss",
            "zombie horse",
            "skeleton horse",
            "mooshroom",
            "silverfish",
            "creeper",
            "explosive creeper",
            "mini zombie",
            "giant",
            "silverfish",
            "beacon"
        ];
        const structures = [
            "village",
            "desert temple",
            "jungle temple",
            "mineshaft",
            "stronghold",
            "end city",
            "mansion",
            "ocean monument",
            "ruined portal",
            "bastion remnant",
            "pillager outpost",
            "buried treasure",
            "nether fortress",
            "shipwreck",
            "dungeon",
            "Igloo",
            "swamp hut",
            "fortress",
            "looted village",
            "ancient city",
            "small village",
            "large village",
            "trader llama",
            "end gateway",
            "village well",
            "pillager outpost tower",
            "woodland mansion",
            "stray spawner",
            "cave system",
            "mineshaft with spiders",
            "mountain cave",
            "temple ruins",
            "fossil",
            "giant tree taiga",
            "beach house",
            "nether bastion",
            "crimson forest",
            "warped forest",
            "ruined portal structures",
            "sand village",
            "snow village",
            "stone village",
            "swamp village",
            "desert village",
            "jungle village",
            "savanna village",
            "acacia village",
            "taiga village"
        ];
        let chosenTask = task[Math.floor(Math.random() * task.length)];
        for (let i = 0; i < 5; i++) {
            chosenTask = chosenTask.replace("#material#", material[Math.floor(Math.random() * material.length)]);
            chosenTask = chosenTask.replace("#block#", block[Math.floor(Math.random() * block.length)]);
            chosenTask = chosenTask.replace("#build#", build[Math.floor(Math.random() * build.length)]);
            chosenTask = chosenTask.replace("#mob#", mobs[Math.floor(Math.random() * mobs.length)]);
            chosenTask = chosenTask.replace("#struc#", structures[Math.floor(Math.random() * structures.length)]);
        }
        await interaction.editReply(chosenTask);
    }
}
